### ISSUE TITLE
Fix langchain-community to >= 0.2.5

### ISSUE THREAD

**Issue by luarss** [The-OpenROAD-Project/ORAssistant#3]
https://github.com/The-OpenROAD-Project/ORAssistant/security/dependabot/2

Due to dependabot alert. @palaniappan-r Do make sure that this upgrade doesn't break anything

**Comment by palaniappan-r** [comment]
I've addressed this in [this branch]( https://github.com/The-OpenROAD-Project/ORAssistant/tree/ensemble-retriever-update). Will make the PR soon.
