### ISSUE TITLE
GitHub Discussions HF dataset

### ISSUE THREAD

**Issue by palaniappan-r** [The-OpenROAD-Project/ORAssistant#47]
Currently, scraped GitHub discussions are in the `data` folder. Move this to a HF dataset.

- [ ] Uploading files to HF Dataset. Link: https://huggingface.co/datasets/The-OpenROAD-Project/ORQA_discussions
- [ ] Use huggingface_hub to pull the dataset during `build_docs`. 
- [ ] Remove data files
- [ ] Rename `Feature Request` to `FeatureRequest` in code -> no space

**Comment by luarss** [comment]
@palaniappan-r HF repo is populated with files: https://huggingface.co/datasets/The-OpenROAD-Project/ORQA_discussions

**Comment by luarss** [comment]
Will be tracked in #67
